name: Renode Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instal depedencie
      
        run: |
          sudo apt update
          sudo apt install git automake cmake autoconf libtool g++ coreutils policykit-1 \
          libgtk-3-dev uml-utilities gtk-sharp3 python3 python3-pip

      - name: Run build
        # Install the Zephyr host build dependencies, and the `west` Python tool.
        # This list is from Zephyr's getting started guide:
        # https://docs.zephyrproject.org/latest/develop/getting_started/index.html
        run: |
          ./build.sh --no-gui --net --host-arch aarch64
      - name: 📦 Save Build Artifacts app
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-app
          path: ${{ github.workspace }}/renode/renode/src/Infrastructure/src/*.dll
